# Generated by Django 6.0.8 on 2026-09-08 06:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationInvite',
            fields=[
                ('invite_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_code_hash', models.CharField(max_length=200)),
                ('code_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('applicant_first_name', models.CharField(max_length=50)),
                ('applicant_last_name', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('contact_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('mode', models.CharField(choices=[('walk_in', 'walk_in'), ('remote', 'remote')], default='remote', max_length=10)),
                ('issued_by_user_id', models.BigIntegerField(db_index=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_by_application_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'application_invites',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['expires_at'], name='application_expires_6d9de9_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('student_application_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('submission_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('lrn', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(db_index=True, default='', max_length=50)),
                ('birth_date', models.DateField(blank=True, db_index=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('contact_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('duplicate_of_student_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('duplicate_matches_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('in_review', 'in_review'), ('approved', 'approved'), ('rejected', 'rejected')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reviewed_by_user_id', models.BigIntegerField(blank=True, null=True)),
                ('decided_by_user_id', models.BigIntegerField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('created_student_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='intake.applicationinvite')),
            ],
            options={
                'db_table': 'student_applications',
                'ordering': ['-submitted_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='student_app_status_a2daa1_idx'), models.Index(fields=['last_name', 'first_name'], name='student_app_last_na_180009_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), _negated=True), ('created_student_id__isnull', False), _connector='OR'), name='student_application_approved_has_student'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), models.Q(models.Q(('decision_note', ''), _negated=True), ('decision_note__isnull', False)), _connector='OR'), name='student_application_rejected_has_note')],
            },
        ),
    ]
