# Generated by Django 6.0.5 on 2026-05-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=30, unique=True)),
                ('subject_name', models.CharField(max_length=150)),
                ('school_level', models.CharField(choices=[('nursery', 'Nursery'), ('kindergarten', 'Kindergarten'), ('elementary', 'Elementary'), ('junior_highschool', 'Junior High School'), ('senior_highschool', 'Senior High School')], max_length=20)),
                ('grade_level', models.CharField(max_length=20)),
                ('strand', models.CharField(blank=True, max_length=50, null=True)),
                ('semester', models.CharField(blank=True, choices=[('1st', '1st Semester'), ('2nd', '2nd Semester')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ('school_level', 'grade_level', 'subject_name'),
                'managed': False,
            },
        ),
    ]
