# Generated by Django 6.0.5 on 2026-07-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_invoice_enrollment_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('discount_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('discount_code', models.CharField(max_length=50, unique=True)),
                ('discount_name', models.CharField(max_length=150)),
                ('discount_mode', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'discount_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('fee_schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('school_level', models.CharField(choices=[('nursery', 'Nursery'), ('kindergarten', 'Kindergarten'), ('elementary', 'Elementary'), ('junior_highschool', 'Junior High School'), ('senior_highschool', 'Senior High School')], max_length=20)),
                ('grade_level', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fee_schedules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeeScheduleItem',
            fields=[
                ('fee_schedule_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_category', models.CharField(choices=[('tuition', 'Tuition'), ('misc', 'Miscellaneous'), ('other', 'Other')], max_length=20)),
                ('item_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'fee_schedule_items',
                'ordering': ('item_category', 'sort_order', 'fee_schedule_item_id'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceInstallment',
            fields=[
                ('installment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('voided', 'Voided')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'invoice_installments',
                'ordering': ('invoice_id', 'sequence'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentInvoice',
            fields=[
                ('invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enrollment_id', models.BigIntegerField()),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('void', 'Void')], default='unpaid', max_length=20)),
                ('payment_plan', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-annual'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentInvoiceDiscount',
            fields=[
                ('invoice_discount_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'student_invoice_discounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentInvoiceItem',
            fields=[
                ('invoice_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('billing_item_id', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'student_invoice_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('gcash', 'GCash'), ('card', 'Card'), ('check', 'Check'), ('others', 'Others')], max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_payments',
                'managed': False,
            },
        ),
    ]
