# Generated by Django 6.0.4 on 2026-08-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('setting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('current_school_year', models.CharField(max_length=20)),
                ('sy_start_date', models.DateField()),
                ('sy_end_date', models.DateField()),
                ('early_bird_days', models.IntegerField(default=7)),
                ('school_name', models.CharField(default='South Lakes Integrated School', max_length=150)),
                ('school_address', models.TextField(blank=True, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'school_settings',
                'managed': False,
            },
        ),
    ]
