# Generated by Django 6.0.5 on 2026-05-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentScholarship',
            fields=[
                ('enrollment_scholarship_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enrollment_scholarships',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScholarshipType',
            fields=[
                ('scholarship_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scholarship_code', models.CharField(max_length=50, unique=True)),
                ('scholarship_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_mode', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'scholarship_types',
                'ordering': ('scholarship_name',),
                'managed': False,
            },
        ),
    ]
