# Generated by Django 6.0.5 on 2026-07-18 09:07

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('guardian_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('relationship', models.CharField(choices=[('mother', 'mother'), ('father', 'father'), ('guardian', 'guardian')], max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=150, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'guardians',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('household_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parent_marital_status', models.CharField(blank=True, choices=[('married', 'married'), ('separated', 'separated'), ('annulled', 'annulled'), ('single_parent', 'single_parent'), ('widowed', 'widowed')], max_length=30, null=True)),
                ('living_arrangement', models.CharField(blank=True, choices=[('both_parents', 'both_parents'), ('mother_only', 'mother_only'), ('father_only', 'father_only'), ('guardian', 'guardian'), ('relative', 'relative'), ('independent', 'independent'), ('others', 'others')], max_length=30, null=True)),
                ('is_4ps_beneficiary', models.BooleanField(default=False)),
                ('four_ps_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'households',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreviousSchool',
            fields=[
                ('previous_school_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=150)),
                ('school_address', models.TextField()),
            ],
            options={
                'db_table': 'previous_schools',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequirementType',
            fields=[
                ('requirement_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('requirement_code', models.CharField(max_length=50, unique=True)),
                ('requirement_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'requirement_types',
                'ordering': ('requirement_name',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sibling',
            fields=[
                ('sibling_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'siblings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('lrn', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(100)])),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('transferred', 'transferred'), ('graduated', 'graduated'), ('dropped', 'dropped')], default='active', max_length=20)),
                ('current_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentRequirementSubmission',
            fields=[
                ('student_requirement_submission_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_submitted', models.BooleanField(default=False)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'student_requirement_submissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentSibling',
            fields=[
                ('student_sibling_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('relationship_note', models.CharField(default='sibling', max_length=20)),
            ],
            options={
                'db_table': 'student_siblings',
                'managed': False,
            },
        ),
    ]
