# Generated by Django 6.0.4 on 2026-09-01 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentExtraction',
            fields=[
                ('document_extraction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('requirement_code', models.CharField(db_index=True, max_length=50)),
                ('family', models.CharField(blank=True, max_length=50, null=True)),
                ('source_label', models.CharField(default='', max_length=150)),
                ('extracted_json', models.JSONField(blank=True, default=dict)),
                ('field_confidence_json', models.JSONField(blank=True, default=dict)),
                ('blocks_json', models.JSONField(blank=True, default=list)),
                ('document_type_seen', models.CharField(blank=True, max_length=100, null=True)),
                ('is_expected_document', models.BooleanField(default=True)),
                ('source_engine', models.CharField(choices=[('paddle', 'PaddleOCR (local)'), ('groq', 'Groq vision (fallback)')], default='paddle', max_length=20)),
                ('mean_confidence', models.FloatField(blank=True, null=True)),
                ('scanned_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_extractions', to='students.student')),
            ],
            options={
                'db_table': 'document_extractions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'requirement_code'], name='document_ex_student_78f1c7_idx')],
            },
        ),
    ]
