# Generated by Django 6.0.5 on 2026-05-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradingComponent',
            fields=[
                ('grading_component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('component_name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'grading_components',
                'ordering': ['sort_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GradingTemplate',
            fields=[
                ('grading_template_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('school_level', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grading_templates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreEntry',
            fields=[
                ('score_entry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grading_period', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'score_entries',
                'managed': False,
            },
        ),
    ]
