# Generated by Django 6.0.5 on 2026-09-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendar', '0002_add_event_type_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='grading_period',
            field=models.CharField(blank=True, choices=[('1st_quarter', '1st Quarter'), ('2nd_quarter', '2nd Quarter'), ('3rd_quarter', '3rd Quarter'), ('4th_quarter', '4th Quarter')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('holiday', 'Holiday'), ('exam', 'Exam / Assessment'), ('enrollment', 'Enrollment Period'), ('quarter_break', 'Quarter Break'), ('school_day_off', 'School Day Off'), ('event', 'Event'), ('grading_period', 'Grading Period'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.UniqueConstraint(condition=models.Q(('grading_period__isnull', False)), fields=('school_year', 'grading_period'), name='uniq_calendar_grading_period_per_year'),
        ),
    ]
