# Generated by Django 6.0.5 on 2026-05-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('school_year', models.CharField(max_length=20)),
                ('school_level', models.CharField(choices=[('nursery', 'Nursery'), ('kindergarten', 'Kindergarten'), ('elementary', 'Elementary'), ('junior_highschool', 'Junior High School'), ('senior_highschool', 'Senior High School')], max_length=20)),
                ('grade_level', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=50)),
                ('strand', models.CharField(blank=True, max_length=50, null=True)),
                ('semester', models.CharField(blank=True, choices=[('1st', '1st Semester'), ('2nd', '2nd Semester')], max_length=20, null=True)),
                ('enrollment_status', models.CharField(choices=[('enrolled', 'Enrolled'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='enrolled', max_length=20)),
            ],
            options={
                'db_table': 'enrollments',
                'ordering': ['-enrollment_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_number', models.CharField(max_length=30, unique=True)),
                ('lrn', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
