# Generated by Django 6.0.4 on 2026-07-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentOverride',
            fields=[
                ('enrollment_override_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('override_reason', models.TextField()),
                ('overridden_by', models.IntegerField()),
                ('overridden_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enrollment_overrides',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectionAdvisory',
            fields=[
                ('advisory_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('teacher_user_id', models.BigIntegerField(db_index=True)),
                ('school_year', models.CharField(max_length=20)),
                ('school_level', models.CharField(choices=[('nursery', 'Nursery'), ('kindergarten', 'Kindergarten'), ('elementary', 'Elementary'), ('junior_highschool', 'Junior High School'), ('senior_highschool', 'Senior High School')], max_length=20)),
                ('grade_level', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=50)),
                ('strand', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'section_advisories',
                'managed': True,
                'unique_together': {('teacher_user_id', 'school_year', 'school_level', 'grade_level', 'section', 'strand')},
            },
        ),
    ]
