# Generated by Django 6.0.4 on 2026-07-17 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_enrollmentoverride_sectionadvisory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentTransfer',
            fields=[
                ('transfer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transfer_type', models.CharField(choices=[('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('internal_move', 'Internal Move')], max_length=20)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('from_grade_level', models.CharField(blank=True, max_length=20, null=True)),
                ('from_section', models.CharField(blank=True, max_length=50, null=True)),
                ('from_strand', models.CharField(blank=True, max_length=50, null=True)),
                ('to_grade_level', models.CharField(blank=True, max_length=20, null=True)),
                ('to_section', models.CharField(blank=True, max_length=50, null=True)),
                ('to_strand', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_school_name', models.CharField(blank=True, max_length=150, null=True)),
                ('origin_school_name', models.CharField(blank=True, max_length=150, null=True)),
                ('initiated_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='enrollments.enrollment')),
            ],
            options={
                'db_table': 'enrollment_transfers',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
