# Generated by Django 6.0.4 on 2026-09-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_enrollmenttransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeliveryFailure',
            fields=[
                ('email_delivery_failure_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_delivery_failures',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
