"""
The school year registry.

Adopts `school_years` rather than simply creating it. Databases that once ran
an abandoned branch (commit 3788efeb, never merged) already have the table,
filled by that branch's own backfill with 2024-2025 through 2029-2030 and the
current flag stuck on 2029-2030. Fresh databases don't have it. Both end up
in the same place:

  1. The table exists with this model's columns and constraints.
  2. Its rows are what this database actually uses: the School Settings year
     becomes the current year with its configured dates, and every other year
     already on a record is registered on the July-June calendar. The
     abandoned branch's rows are discarded -- nobody set them up.
  3. That branch's two rows in django_migrations (enrollments 0003_schoolyear,
     0004_backfill_school_years) are removed; they name migrations this
     codebase doesn't have.

The foreign keys that hold other tables to this one are 0006.
"""
import re
from datetime import date

from django.db import migrations, models
from django.utils import timezone

LABEL_RE = re.compile(r"^(\d{4})-(\d{4})$")

# Tables whose school_year must name a registered year (see 0006).
LABELLED_TABLES = (
    "enrollments",
    "section_advisories",
    "academic_calendar_events",
    "risk_assessment_runs",
)

ADOPT_TABLE = """
CREATE TABLE IF NOT EXISTS school_years (
    school_year_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label          varchar(20) NOT NULL,
    start_date     date NOT NULL,
    end_date       date NOT NULL,
    is_current     boolean NOT NULL,
    created_at     timestamp with time zone NOT NULL,
    updated_at     timestamp with time zone NOT NULL
);
ALTER TABLE school_years ADD COLUMN IF NOT EXISTS archived_at timestamp with time zone NULL;
ALTER TABLE school_years ADD COLUMN IF NOT EXISTS archived_by bigint NULL;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'school_years_label_key') THEN
        ALTER TABLE school_years ADD CONSTRAINT school_years_label_key UNIQUE (label);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'school_years_start_before_end') THEN
        ALTER TABLE school_years
            ADD CONSTRAINT school_years_start_before_end CHECK (start_date < end_date);
    END IF;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS uniq_current_school_year
    ON school_years (is_current) WHERE is_current;
"""

FORGET_ABANDONED_MIGRATIONS = """
DELETE FROM django_migrations
 WHERE app = 'enrollments'
   AND name IN ('0003_schoolyear', '0004_backfill_school_years');
"""


def _valid(label):
    match = LABEL_RE.match(label or "")
    return bool(match) and int(match.group(2)) == int(match.group(1)) + 1


def register_years(apps, schema_editor):
    connection = schema_editor.connection
    now = timezone.now()

    with connection.cursor() as cur:
        tables = set(connection.introspection.table_names(cur))
        cur.execute("DELETE FROM school_years")

        def insert(label, start, end, is_current):
            cur.execute(
                """
                INSERT INTO school_years
                    (label, start_date, end_date, is_current, created_at, updated_at)
                VALUES (%s, %s, %s, %s, %s, %s)
                ON CONFLICT (label) DO NOTHING
                """,
                [label, start, end, is_current, now, now],
            )

        # 1) The configured year becomes the current one, keeping its dates.
        if "school_settings" in tables:
            cur.execute(
                "SELECT current_school_year, sy_start_date, sy_end_date "
                "FROM school_settings ORDER BY setting_id LIMIT 1"
            )
            row = cur.fetchone()
            if row:
                label = (row[0] or "").strip()
                start, end = row[1], row[2]
                if _valid(label) and start and end and start < end:
                    insert(label, start, end, True)

        # 2) Every other year a record already uses. 0006 couldn't add its
        # foreign keys otherwise, and dropping those rows isn't a migration's
        # call to make.
        labels = set()
        for table in LABELLED_TABLES:
            if table in tables:
                cur.execute(
                    f"SELECT DISTINCT school_year FROM {table} WHERE school_year IS NOT NULL"
                )
                labels.update((r[0] or "").strip() for r in cur.fetchall())
        for label in sorted(labels):
            if _valid(label):
                first = int(label[:4])
                insert(label, date(first, 7, 1), date(first + 1, 6, 30), False)


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0004_emaildeliveryfailure"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="SchoolYear",
                    fields=[
                        ("school_year_id", models.BigAutoField(primary_key=True, serialize=False)),
                        ("label", models.CharField(max_length=20, unique=True)),
                        ("start_date", models.DateField()),
                        ("end_date", models.DateField()),
                        ("is_current", models.BooleanField(default=False)),
                        ("archived_at", models.DateTimeField(blank=True, null=True)),
                        ("archived_by", models.BigIntegerField(blank=True, null=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "db_table": "school_years",
                        "ordering": ["-label"],
                        "managed": True,
                        "constraints": [
                            models.UniqueConstraint(
                                condition=models.Q(is_current=True),
                                fields=("is_current",),
                                name="uniq_current_school_year",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(start_date__lt=models.F("end_date")),
                                name="school_years_start_before_end",
                            ),
                        ],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(ADOPT_TABLE, reverse_sql="DROP TABLE IF EXISTS school_years;"),
            ],
        ),
        migrations.RunPython(register_years, migrations.RunPython.noop),
        migrations.RunSQL(FORGET_ABANDONED_MIGRATIONS, reverse_sql=migrations.RunSQL.noop),
    ]
