# Generated by Django 6.0.8 on 2026-09-25 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_emaildeliveryfailure'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianResponse',
            fields=[
                ('guardian_response_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('response', models.CharField(choices=[('returning', 'Returning'), ('not_returning', 'Not returning')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('responded_by', models.IntegerField()),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(db_column='enrollment_id', on_delete=django.db.models.deletion.CASCADE, related_name='guardian_response', to='enrollments.enrollment')),
            ],
            options={
                'db_table': 'guardian_responses',
                'managed': True,
            },
        ),
    ]
