# Generated by Django 6.0.8 on 2026-09-15 07:21

from django.db import migrations, models

# State-only. GuardianMirror is managed=False (accounts/guardian_mirror.py), so
# this issues no DDL -- the `guardians` table stays owned by student-service.
# It exists only because the model is imported at app load here (unlike
# billing's twin, which is imported lazily), so makemigrations --check fails
# without it.


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_current_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianMirror',
            fields=[
                ('guardian_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email_address', models.CharField(blank=True, max_length=150, null=True)),
                ('relationship', models.CharField(max_length=20)),
                ('is_primary_contact', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'guardians',
                'managed': False,
            },
        ),
    ]
