# Generated by Django 6.0.5 on 2026-05-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grading_period', models.CharField(choices=[('1st_quarter', '1st Quarter'), ('2nd_quarter', '2nd Quarter'), ('3rd_quarter', '3rd Quarter'), ('4th_quarter', '4th Quarter'), ('1st_semester', '1st Semester'), ('2nd_semester', '2nd Semester')], max_length=20)),
                ('numeric_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remarks', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed'), ('incomplete', 'Incomplete'), ('dropped', 'Dropped')], max_length=20, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grades',
                'ordering': ('enrollment_id', 'subject__subject_name', 'grading_period'),
                'managed': False,
            },
        ),
    ]
