# Generated by Django 6.0.5 on 2026-07-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_narrative_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='narrativereport',
            options={'managed': False, 'ordering': ['category__sort_order', 'category__name']},
        ),
    ]
