# Generated by Django 6.0.5 on 2026-07-18 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementType',
            fields=[
                ('requirement_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('requirement_code', models.CharField(max_length=50, unique=True)),
                ('requirement_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'requirement_types',
                'ordering': ('requirement_name',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentRequirementSubmission',
            fields=[
                ('student_requirement_submission_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_id', models.BigIntegerField(db_index=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'student_requirement_submissions',
                'ordering': ('requirement_type__requirement_name',),
                'managed': False,
            },
        ),
    ]
