# Generated by Django 6.0.4 on 2026-07-11 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessmentRun',
            fields=[
                ('run_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('school_year', models.CharField(max_length=20)),
                ('grading_period', models.CharField(max_length=20)),
                ('school_level', models.CharField(blank=True, max_length=20, null=True)),
                ('grade_level', models.CharField(blank=True, max_length=20, null=True)),
                ('weights_json', models.JSONField(default=dict)),
                ('triggered_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'risk_assessment_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRiskScore',
            fields=[
                ('score_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_id', models.BigIntegerField(db_index=True)),
                ('enrollment_id', models.BigIntegerField(db_index=True)),
                ('grade_component', models.FloatField(blank=True, null=True)),
                ('attendance_component', models.FloatField(blank=True, null=True)),
                ('narrative_component', models.FloatField(blank=True, null=True)),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='ai.riskassessmentrun')),
            ],
            options={
                'db_table': 'student_risk_scores',
                'ordering': ['-risk_score'],
                'unique_together': {('run', 'student_id')},
            },
        ),
    ]
