# Generated by Django 6.0.4 on 2026-09-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_risk_score_trend_and_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentriskscore',
            name='attendance_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentriskscore',
            name='average_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentriskscore',
            name='failing_subject_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentriskscore',
            name='grade_delta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
